/*
 * buttons.h
 *
 * Created: 11/10/2014 4:05:43 PM
 *  Author: Jonathon
 */ 

#include "gameboy.h"

// BUTTON SETUP
#define UP_BUTTON_DIR(DIR) SET(DDRA,_BV(PINA5),DIR)
#define DOWN_BUTTON_DIR(DIR) SET(DDRA,_BV(PINA6),DIR)
#define LEFT_BUTTON_DIR(DIR) SET(DDRA,_BV(PINA7),DIR)
#define RIGHT_BUTTON_DIR(DIR) SET(DDRA,_BV(PINA4),DIR)
#define A_BUTTON_DIR(DIR) SET(DDRA,_BV(PINA2),DIR)
#define B_BUTTON_DIR(DIR) SET(DDRA,_BV(PINA1),DIR)
#define C_BUTTON_DIR(DIR) SET(DDRA,_BV(PINA0),DIR)
#define VBATT_DIR(DIR) SET(DDRA,_BV(PINA3),DIR)

#define UP_BUTTON ~GET(PINA,_BV(PINA5))
#define UP_BUTTON_PULLUP() SET(PORTA, _BV(PINA5),ON)
#define DOWN_BUTTON ~GET(PINA,_BV(PINA6))
#define DOWN_BUTTON_PULLUP() SET(PORTA, _BV(PINA6),ON)
#define LEFT_BUTTON ~GET(PINA,_BV(PINA7))
#define LEFT_BUTTON_PULLUP() SET(PORTA, _BV(PINA7),ON)
#define RIGHT_BUTTON ~GET(PINA,_BV(PINA4))
#define RIGHT_BUTTON_PULLUP() SET(PORTA, _BV(PINA4),ON)
#define A_BUTTON ~GET(PINA,_BV(PINA2))
#define A_BUTTON_PULLUP() SET(PORTA, _BV(PINA2),ON)
#define B_BUTTON ~GET(PINA,_BV(PINA1))
#define B_BUTTON_PULLUP() SET(PORTA, _BV(PINA1),ON)
#define C_BUTTON ~GET(PINA,_BV(PINA0))
#define C_BUTTON_PULLUP() SET(PORTA, _BV(PINA0),ON)

//BATTERY LED SETUP
#define BAT_LOW_LED_DIR(DIR) SET(DDRC,_BV(PINC6),DIR)
#define BAT_LOW_LED(STATE) SET(PORTC,_BV(PINC6),STATE)
#define BAT_LOW_LED_VAL GET(PINC,_BV(PINC6))


// BUTTON FUNCS
void init_gpio(void);